/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ClipboardFormat {
  id: number
  name?: string
}
export function getClipboardData(format: number): Buffer
export function getClipboardFormatName(format: number): string | null
export function getClipboardFormats(): Array<ClipboardFormat>
